- id: nfs-server
  type: group
  role: [ nfs-server ]
  parameters:
    strategy:
      type: parallel

- id: top-role-nfs
  type: puppet
  groups: [nfs-server]
  required_for: [deploy_end]
  requires: [fuel_pkgs, hiera, globals, logging, tools, netconfig, connectivity_tests, firewall, ssl-keys-saving, ssl-add-trust-chain, hosts, zabbix]
  parameters:
    puppet_manifest: puppet/manifests/deploy.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800



