- id: nfs-server
  type: group
  role: [ nfs-server ]
  tasks: [fuel_pkgs, hiera, globals, logging, tools, netconfig, connectivity_tests, firewall, ssl-keys-saving, ssl-add-trust-chain, hosts]
  parameters:
    strategy:
      type: parallel

- id: top-role-nfs
  type: puppet
  groups: [nfs-server]
  required_for: [deploy_end]
  requires: [hosts, firewall]
  parameters:
    puppet_manifest: puppet/manifests/deploy.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: fw-role-nfs
  type: puppet
  groups: [nfs-server]
  required_for: [post_deployment_end]
  requires: [post_deployment_start]
  parameters:
    puppet_manifest: puppet/manifests/post_deploy.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800


